version: '3.8'
services:
  database:
    image: 'postgres:13-alpine'
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=rpc
      - POSTGRES_DB=rpc
    ports:
      - '54320:5432'
    volumes:
      - ~/Docker/Volumes/rpc:/var/lib/postgresql/data
    networks:
      - database
    restart: unless-stopped

networks:
  database:
    driver: bridge
